print("========================================================")
print("|           Refinery control v0.1 alpha                |")
print("========================================================")
print(" 1.Oil tanks Control Program                           |")
print(" 2.Water tanks Control Program                         |")
print(" 3.Fuel Tanks Control Program                          |")
print(" 4.Generator Control Program                           |")
print(" 5.Refinery Control Program                            |")
print(" 6.Exit Refinery Control                               |")
print("========================================================")
